version: '3.8'
services:
  frontend:
   build:
     context: ./ORSProject10-UI Fctl
   ports:
    - 80:80

backend:
  build:
    context: ./projectORS
  ports:
    - "8080:8080"
  depends_on:
     - MySQL
  environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/ors_p10
     - SPRING_DATASOURCE_USERNAME=root
     - SPRING_DATASOURCE_PASSWORD=rootpassword

mysql: 
  image: mysql:8.1
  container_name: mysql
  environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ors_p10
  volumes:
    - mysql_data:/var/lib/mysql

volumes:
 mysql_data:
             
